/* eslint-disable no-unused-vars */
export enum POS {
  Noun = 'Noun',
  Pronoun = 'Pronoun',
  Verb = 'Verb',
  Adjective = 'Adjective',
  Adverb = 'Adverb',
  Preposition = 'Preposition',
  Conjuction = 'Conjuction',
  Determiner = 'Determiner',
  Counter = 'Counter',
  Numeral = 'Numeral'
}

export const ALL_POS_DEFAULT = Object.values(POS) as string[];

export enum NodeType {
  Word = 'word',
  Roman = 'romanized',
  Form = 'form',
  POS = 'pos',
  Language = 'language',
  Text = 'text'
}
export const NodeTypeList = Object.values(NodeType);

export enum EdgeType {
  Means = 'means',
  Antonym = 'antonym',
  IsPOS = 'is:pos',
  IsLanguage = 'is:language',
  IsForm = 'is:form',
  Romanization = 'romanize'
}

export const EdgeTypeList = Object.values(EdgeType);
export const twoWaysEdge = new Set([
  EdgeType.Means,
  EdgeType.Antonym,
  EdgeType.IsForm,
]);

export enum EditorState {
  NoWordSelected,
  WordSelected,
  NonWordSelected,
}

export const ALL_LANGUAGES_DEFAULT = [
  'Afrikaans',
  'Albanian',
  'Amharic',
  'Arabic',
  'Aragonese',
  'Armenian',
  'Asturian',
  'Azerbaijani',
  'Basque',
  'Belarusian',
  'Bengali',
  'Bosnian',
  'Breton',
  'Bulgarian',
  'Catalan',
  'Central Kurdish',
  'Chinese',
  'Simplified Chinese',
  'Traditional Chinese',
  'Corsican',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch',
  'English',
  'Esperanto',
  'Estonian',
  'Faroese',
  'Filipino',
  'Finnish',
  'French',
  'Galician',
  'Georgian',
  'German',
  'Greek',
  'Guarani',
  'Gujarati',
  'Hausa',
  'Hawaiian',
  'Hebrew',
  'Hindi',
  'Hungarian',
  'Icelandic',
  'Indonesian',
  'Interlingua',
  'Irish',
  'Italian',
  'Japanese',
  'Kannada',
  'Kazakh',
  'Khmer',
  'Korean',
  'Kurdish',
  'Kyrgyz',
  'Lao',
  'Latin',
  'Latvian',
  'Lingala',
  'Lithuanian',
  'Macedonian',
  'Malay',
  'Malayalam',
  'Maltese',
  'Marathi',
  'Mongolian',
  'Nepali',
  'Norwegian',
  'Occitan',
  'Oriya',
  'Oromo',
  'Pashto',
  'Persian',
  'Polish',
  'Portuguese',
  'Punjabi',
  'Quechua',
  'Romanian',
  'Romansh',
  'Russian',
  'Scottish Gaelic',
  'Serbian',
  'Serbo',
  'Shona',
  'Sindhi',
  'Sinhala',
  'Slovak',
  'Slovenian',
  'Somali',
  'Southern Sotho',
  'Spanish',
  'Sundanese',
  'Swahili',
  'Swedish',
  'Tajik',
  'Tamil',
  'Tatar',
  'Telugu',
  'Thai',
  'Tigrinya',
  'Tongan',
  'Turkish',
  'Turkmen',
  'Twi',
  'Ukrainian',
  'Urdu',
  'Uyghur',
  'Uzbek',
  'Vietnamese',
  'Walloon',
  'Welsh',
  'Western Frisian',
  'Xhosa',
  'Yiddish',
  'Yoruba',
  'Zulu'
];
